name: topkd
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _pytorch_select=0.1
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - attrs=21.4.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.4
  - ca-certificates=2023.05.30
  - certifi=2022.12.7
  - cffi=1.15.0
  - cudatoolkit=10.1.243
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dionysus=2.0.8
  - entrypoints=0.4
  - expat=2.4.4
  - flit-core=3.7.1
  - fontconfig=2.13.1
  - freetype=2.11.0
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=3.7.0
  - hdf5=1.10.6
  - icu=58.2
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - importlib_resources=5.2.0
  - intel-openmp=2021.4.0
  - ipykernel=6.15.2
  - ipython=7.33.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.1
  - jinja2=3.0.3
  - jpeg=9e
  - jupyter=1.0.0
  - jupyter_client=7.2.2
  - jupyter_console=6.4.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=11.2.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libuv=1.40.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.15
  - libxml2=2.9.14
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - nbclient=0.5.13
  - nbconvert=6.4.4
  - nbformat=5.3.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - ninja=1.10.2
  - ninja-base=1.10.2
  - notebook=6.4.11
  - numexpr=2.8.1
  - numpy=1.21.5
  - numpy-base=1.21.5
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1u
  - packaging=21.3
  - pandas=1.3.5
  - pandoc=2.18
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.2.0
  - pip=22.2
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pycparser=2.21
  - pygments=2.12.0
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - pyrsistent=0.18.0
  - python=3.7.11
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.1
  - python_abi=3.7
  - pytorch=1.7.1
  - pytz=2022.1
  - pyzmq=22.3.0
  - qt=5.9.7
  - qtconsole=5.3.0
  - qtconsole-base=5.3.0
  - qtpy=2.0.1
  - readline=8.1.2
  - scipy=1.7.3
  - send2trash=1.8.0
  - setuptools=59.8.0
  - sip=4.19.8
  - six=1.16.0
  - soupsieve=2.3.1
  - sqlite=3.38.3
  - terminado=0.13.1
  - testpath=0.5.0
  - tk=8.6.12
  - tornado=6.1
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.8.0
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - absl-py==2.0.0
    - aiofiles==22.1.0
    - aiosqlite==0.19.0
    - anyio==3.7.1
    - appdirs==1.4.4
    - arrow==1.2.3
    - astunparse==1.6.3
    - babel==2.13.1
    - cached-property==1.5.2
    - cachetools==5.3.2
    - charset-normalizer==3.2.0
    - click==8.1.6
    - docker-pycreds==0.4.0
    - exceptiongroup==1.2.0
    - flatbuffers==23.5.26
    - fqdn==1.5.1
    - gast==0.4.0
    - gitdb==4.0.10
    - gitpython==3.1.32
    - google-auth==2.25.2
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.60.0
    - gudhi==3.8.0
    - idna==3.4
    - ipdb==0.13.13
    - isoduration==20.11.0
    - json5==0.9.14
    - jsonpointer==2.4
    - jsonschema==4.17.3
    - jupyter-core==4.12.0
    - jupyter-events==0.6.3
    - jupyter-server==1.24.0
    - jupyter-server-fileid==0.9.0
    - jupyter-server-ydoc==0.8.0
    - jupyter-ydoc==0.2.5
    - jupyterlab==3.6.6
    - jupyterlab-server==2.24.0
    - jupyterthemes==0.20.0
    - keras==2.11.0
    - lesscpy==0.15.1
    - libclang==16.0.6
    - markdown==3.4.4
    - nbclassic==1.0.0
    - notebook-shim==0.2.3
    - oauthlib==3.2.2
    - opt-einsum==3.3.0
    - pathtools==0.1.2
    - pkgutil-resolve-name==1.3.10
    - ply==3.11
    - protobuf==3.19.6
    - pyasn1==0.5.1
    - pyasn1-modules==0.3.0
    - python-json-logger==2.0.7
    - pyyaml==6.0.1
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rsa==4.9
    - scikit-learn==1.0.2
    - seaborn==0.12.2
    - sentry-sdk==1.29.2
    - setproctitle==1.3.2
    - smmap==5.0.0
    - sniffio==1.3.0
    - tensorboard==2.11.2
    - tensorboard-data-server==0.6.1
    - tensorboard-logger==0.1.0
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.11.0
    - tensorflow-estimator==2.11.0
    - tensorflow-io-gcs-filesystem==0.34.0
    - termcolor==2.3.0
    - tomli==2.0.1
    - topologylayer==0.0.0
    - torch==1.8.1+cu101
    - torchaudio==0.8.1
    - torchvision==0.9.1+cu101
    - tqdm==4.64.0
    - traitlets==5.9.0
    - uri-template==1.3.0
    - urllib3==2.0.4
    - wandb==0.15.8
    - webcolors==1.13
    - websocket-client==1.6.1
    - werkzeug==2.2.3
    - wrapt==1.16.0
    - y-py==0.6.2
    - ypy-websocket==0.8.4
